# SPDX-License-Identifier: GPL-3.0-or-later
# deglyph
"""
Markdown and single-file HTML report renderers for `deglyph scan` output.

`scan.to_text` is for terminals and `scan.to_sarif` is for code-scanning
ingestion. This module covers the in-between: a markdown report shaped for a
GitHub PR comment, and a self-contained HTML report you can drop on a static
host or attach to a CI run.

Both take the same `[(path, findings)]` shape `scan` returns and group by
severity, then by rule. A clean run renders a "no findings" body so the PR
comment is still useful (and idempotent for sticky-comment updates).

Public: to_markdown, to_html.
"""

from __future__ import annotations

import html
from collections import defaultdict

from . import __version__
from .scan import CATEGORY_LABEL, CATEGORY_ORDER, Finding

_LEVEL_ORDER = ("error", "warning", "note")
_LEVEL_LABELS = {"error": "Errors", "warning": "Warnings", "note": "Notes"}


def _by_level(findings: list[Finding]) -> dict[str, list[Finding]]:
    grouped: dict[str, list[Finding]] = defaultdict(list)
    for f in findings:
        grouped[f.level].append(f)
    return grouped


def _by_category(findings: list[Finding]) -> dict[str, list[Finding]]:
    grouped: dict[str, list[Finding]] = defaultdict(list)
    for f in findings:
        grouped[f.category].append(f)
    return grouped


def _totals(results: list[tuple[str, list[Finding]]]) -> dict[str, int]:
    out: dict[str, int] = {"error": 0, "warning": 0, "note": 0}
    for _p, findings in results:
        for f in findings:
            out[f.level] = out.get(f.level, 0) + 1
    return out


def _summary_line(totals: dict[str, int]) -> str:
    e, w, n = totals.get("error", 0), totals.get("warning", 0), totals.get("note", 0)
    if e == w == n == 0:
        return "0 findings (clean)"
    return f"{e} error(s), {w} warning(s), {n} note(s)"


def to_markdown(
    results: list[tuple[str, list[Finding]]],
    *,
    title: str = "deglyph scan",
) -> str:
    """Render a scan result list as a markdown report suitable for a PR comment."""
    totals = _totals(results)
    lines: list[str] = []
    lines.append(f"## {title}: {_summary_line(totals)}")
    lines.append("")

    if not results:
        lines.append("_No files scanned._")
        return "\n".join(lines) + _footer_md()

    if all(not findings for _p, findings in results):
        lines.append("Clean across all scanned files.")
        return "\n".join(lines) + _footer_md()

    for path, findings in results:
        lines.append(f"### `{path}`")
        if not findings:
            lines.append("_No findings._")
            lines.append("")
            continue
        by_cat = _by_category(findings)
        for cat in CATEGORY_ORDER:
            group = by_cat.get(cat) or []
            if not group:
                continue
            lines.append(f"#### {CATEGORY_LABEL[cat]} ({len(group)})")
            grouped = _by_level(group)
            for level in _LEVEL_ORDER:
                items = grouped.get(level) or []
                if not items:
                    continue
                lines.append(f"**{_LEVEL_LABELS[level]}** ({len(items)})")
                for f in items:
                    lines.append(f"- `{f.rule}` at `{f.where}`: {f.message}")
                lines.append("")

    return "\n".join(lines) + _footer_md()


def _footer_md() -> str:
    return (
        f"\n---\nGenerated by [deglyph](https://deglyph.dev) {__version__}. "
        f"Findings are heuristics; confirm before remediating."
    )


_HTML_STYLE = """\
:root { color-scheme: light dark; }
body { font: 14px/1.5 system-ui, sans-serif; max-width: 960px; margin: 2rem auto; padding: 0 1rem; }
h1 { font-size: 1.4rem; margin-bottom: 0.5rem; }
h2 { font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #8884; padding-bottom: 0.2rem; }
h3 { font-size: 0.95rem; margin-top: 1rem; }
.summary { display: flex; gap: 0.5rem; flex-wrap: wrap; margin: 0.5rem 0 1rem; }
.pill { padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.85rem; font-weight: 600; }
.pill.error { background: #e74c3c22; color: #c0392b; }
.pill.warning { background: #f39c1222; color: #b9770e; }
.pill.note { background: #6c757d22; color: #495057; }
.pill.clean { background: #27ae6022; color: #1e8449; }
table { border-collapse: collapse; width: 100%; margin-bottom: 1rem; font-size: 0.9rem; }
th, td { padding: 0.4rem 0.6rem; text-align: left; vertical-align: top; border-bottom: 1px solid #8882; }
th { font-weight: 600; background: #8881; }
code { font-family: ui-monospace, Menlo, Consolas, monospace; font-size: 0.85em; background: #8881; padding: 0.05em 0.3em; border-radius: 3px; }
.rule-error { color: #c0392b; }
.rule-warning { color: #b9770e; }
.rule-note { color: #495057; }
footer { margin-top: 2rem; font-size: 0.85rem; color: #777; }
footer a { color: inherit; }
"""


def to_html(
    results: list[tuple[str, list[Finding]]],
    *,
    title: str = "deglyph scan",
) -> str:
    """Render a self-contained HTML report (one file, no external assets)."""
    totals = _totals(results)
    body: list[str] = []
    body.append(f"<h1>{html.escape(title)}</h1>")

    if any(totals.values()):
        body.append('<div class="summary">')
        for level in _LEVEL_ORDER:
            count = totals.get(level, 0)
            if count:
                body.append(
                    f'<span class="pill {level}">{count} {_LEVEL_LABELS[level].lower()}</span>'
                )
        body.append("</div>")
    else:
        body.append('<div class="summary"><span class="pill clean">clean</span></div>')

    if not results:
        body.append("<p><em>No files scanned.</em></p>")
    else:
        for path, findings in results:
            body.append(f"<h2><code>{html.escape(path)}</code></h2>")
            if not findings:
                body.append("<p><em>No findings.</em></p>")
                continue
            by_cat = _by_category(findings)
            for cat in CATEGORY_ORDER:
                group = by_cat.get(cat) or []
                if not group:
                    continue
                body.append(f"<h3>{CATEGORY_LABEL[cat]} ({len(group)})</h3>")
                grouped = _by_level(group)
                for level in _LEVEL_ORDER:
                    items = grouped.get(level) or []
                    if not items:
                        continue
                    body.append(f"<h4>{_LEVEL_LABELS[level]} ({len(items)})</h4>")
                    body.append("<table>")
                    body.append(
                        "<tr><th>rule</th><th>location</th><th>message</th></tr>"
                    )
                    for f in items:
                        body.append(
                            "<tr>"
                            f'<td><code class="rule-{level}">'
                            f"{html.escape(f.rule)}</code></td>"
                            f"<td><code>{html.escape(f.where)}</code></td>"
                            f"<td>{html.escape(f.message)}</td>"
                            "</tr>"
                        )
                    body.append("</table>")

    body.append(
        '<footer>Generated by <a href="https://deglyph.dev">deglyph</a> '
        f"{html.escape(__version__)}. Findings are heuristics; confirm before remediating.</footer>"
    )

    return (
        "<!doctype html>\n"
        '<html lang="en"><head>'
        '<meta charset="utf-8">'
        f"<title>{html.escape(title)}</title>"
        f"<style>{_HTML_STYLE}</style>"
        "</head><body>" + "\n".join(body) + "</body></html>\n"
    )


__all__ = ["to_markdown", "to_html"]
